version: '3.3'
services:
  db:
    container_name: dev-db
    image: mariadb:10.6
    volumes:
      - './data/mysql:/var/lib/mysql'
    ports:
      - 18766:3306
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_DATABASE: wordpress
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: notSecureChangeMe

  phpmyadmin:
    container_name: dev-phpmyadmin
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - 88:88
    environment:
      PMA_HOST: 'db:3306'
 
  wordpress:
    container_name: 'local-wordpress'
    depends_on:
      - db
    image: 'wordpress:latest'
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: 'db:3306'
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - "./wordpress:/var/www/html"
      - "./plugins:/var/www/html/wp-content/plugins"